<?php

use Symfony\Component\HttpFoundation\RedirectResponse;

function citp_file_download($uri) {
  if (Drupal::currentUser()->isAnonymous()) {
    $response = new RedirectResponse('/user/login?destination=' . file_url_transform_relative(file_create_url($uri)));
    $response->send();
  } else {
    $fields = [
      'uid' => Drupal::currentUser()->id(),
      'file_url' => file_url_transform_relative(file_create_url($uri)),
      'timestamp' => \Drupal::time()->getRequestTime(), 
    ];
    db_insert('citp_file_downloads')
      ->fields($fields)
      ->execute();
  }
}

use Drupal\Core\Database\Query\AlterableInterface;

/**
 * Implements hook_query_TAG_alter(): tag search_$type with $type node_search.
 */
function citp_query_search_node_search_alter(AlterableInterface $query) {
  // For testing purposes, restrict the query to node type 'article' only.
  $query->condition('n.type', array('it_effort', 'page'), 'IN');
}
